name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Push theme to Shopify
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          shopify theme push --theme $SHOPIFY_FLAG_THEME_ID --store $SHOPIFY_FLAG_STORE --path . --nodelete --allow-live --json
